yolo_version: yolo11
exp_name: defect
data: configs/data/defect.yaml
data_root: /home/ubuntu/project/deduibi/yolo/dataset/yolo/datasetm6c
model: models/pretrained/yolo11m.pt
epochs: 100
imgsz: 640
batch: 10
device: ''
workers: 8
conf: 0.2
nms_iou: 0.7
max_det: 100
match_iou: 0.3
mode: train_test
weights: /home/ubuntu/project/deduibi/yolo/models/defect/exp_2601261106/best/best.pt
patience: 0
lr0: 0.012
lrf: 0.12
warmup_epochs: 0.0
save_train_pic: false
save_val_pic: true
save_test_pic: true
val_split: 0.0
seed: 42
metric_conf: 0.01
eval_batch: 1
eval_device: ''
enhance:
  enable_p2: false
  p2_source: auto
  p2_backbone_select: first
  p2_pan_fuse: true
  enable_bifpn: false
  bifpn_depth: 1
  bifpn_channels: 0
  enable_carafe: true
  carafe_replace_neck: true
  carafe_kernel: 5
  carafe_up_kernel: 3
  carafe_comp_channels: 64
  head_type: base
  head_blocks: 1
  enable_dcn: false
  dcn_scales:
  - 1
  dcn_kernel: 3
threshold_sweep:
  fix: iou
  fix_list:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  curve:
  - 0.01
  - 0.01
  - 1.0
  table:
  - 0.0
  - 0.05
  - 1.0
